/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Proveedor;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevoProveedor;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerProveedor;
import mx.gob.ceasonora.tonerManagement.implementaciones.ProveedorImp;
import mx.gob.ceasonora.tonerManagement.instancias.InstanciaVentana;
import mx.gob.ceasonora.tonerManagement.interfaces.ProveedorInt;

/**
 *
 * @author kevin
 */
public class AdministrarProveedores extends javax.swing.JInternalFrame {
    ProveedorInt pvdImp = new ProveedorImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Nombre", "Telefono", "Correo"};
    List<Proveedor> proveedores;
    public static Proveedor proveedor;
    

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarProveedores() {
        initComponents();
        modelo = new DefaultTableModel();
        proveedoresTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            proveedores = pvdImp.lista_proveedores();
            for(Proveedor pvd: proveedores){
                Object[] o = new Object[4];
                o[0] = pvd.getId();
                o[1] = pvd.getNombre();
                o[2] = pvd.getTelefono();
                o[3] = pvd.getCorreo();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarIdTextField = new javax.swing.JTextField();
        buscarNombreTextField = new javax.swing.JTextField();
        buscarIdButton = new javax.swing.JButton();
        mostrarTodosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        proveedoresTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Proveedores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Buscar por ID:");

        jLabel3.setText("Buscar por Nombre:");

        buscarNombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarNombreTextFieldKeyReleased(evt);
            }
        });

        buscarIdButton.setText("Buscar");
        buscarIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdButtonActionPerformed(evt);
            }
        });

        mostrarTodosButton.setText("Mostrar Todos");
        mostrarTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarIdButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrarTodosButton)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarIdButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mostrarTodosButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proveedoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Telefono", "Correo"
            }
        ));
        jScrollPane1.setViewportView(proveedoresTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevoButton.setText("Nuevo Proveedor");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver/Editar");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(verButton)
                .addGap(69, 69, 69)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(nuevoButton)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosButtonActionPerformed

        try {
            modelo = new DefaultTableModel();
            proveedoresTable.setModel(modelo);
            modelo.setColumnIdentifiers(titulos);
            proveedores = pvdImp.lista_proveedores();
            for (Proveedor pvd : proveedores) {
                Object[] o = new Object[4];
                o[0] = pvd.getId();
                o[1] = pvd.getNombre();
                o[2] = pvd.getTelefono();
                o[3] = pvd.getCorreo();

                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_mostrarTodosButtonActionPerformed

    private void buscarNombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarNombreTextFieldKeyReleased

        try {
            modelo = new DefaultTableModel();
            proveedoresTable.setModel(modelo);
            modelo.setColumnIdentifiers(titulos);
            proveedores = pvdImp.buscar_nombre(buscarNombreTextField.getText());
            for(Proveedor pvd: proveedores){
                Object[] o = new Object[4];
                o[0] = pvd.getId();
                o[1] = pvd.getNombre();
                o[2] = pvd.getTelefono();
                o[3] = pvd.getCorreo();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarNombreTextFieldKeyReleased

    private void buscarIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdButtonActionPerformed

        try {
            modelo = new DefaultTableModel();
            proveedoresTable.setModel(modelo);
            modelo.setColumnIdentifiers(titulos);
            proveedores = pvdImp.buscar_id(Integer.parseInt(buscarIdTextField.getText()));
            for(Proveedor pvd: proveedores){
                Object[] o = new Object[4];
                o[0] = pvd.getId();
                o[1] = pvd.getNombre();
                o[2] = pvd.getTelefono();
                o[3] = pvd.getCorreo();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarIdButtonActionPerformed

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!proveedoresTable.getSelectionModel().isSelectionEmpty()){
            proveedor = proveedores.get(proveedoresTable.getSelectedRow());
            VerProveedor verProveedor = new VerProveedor();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verProveedor)){
                escritorio.add(verProveedor);
                verProveedor.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verProveedor);
            }
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if (!proveedoresTable.getSelectionModel().isSelectionEmpty()) {
            proveedor = proveedores.get(proveedoresTable.getSelectedRow());
            if (proveedor != null) {
                if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el Proveedor " + proveedor.getNombre() + "?", "Eliminar Proveedor", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
                    try {
                        if (pvdImp.Eliminar(proveedor)) {
                            JOptionPane.showMessageDialog(null, "Proveedor eliminado con éxito", "Proveedor eliminado", JOptionPane.INFORMATION_MESSAGE);
                            modelo = new DefaultTableModel();
                            proveedoresTable.setModel(modelo);
                            modelo.setColumnIdentifiers(titulos);
                            proveedores = pvdImp.lista_proveedores();
                            for (Proveedor pvd : proveedores) {
                                Object[] o = new Object[4];
                                o[0] = pvd.getId();
                                o[1] = pvd.getNombre();
                                o[2] = pvd.getTelefono();
                                o[3] = pvd.getCorreo();

                                modelo.addRow(o);
                            }
                        }
                    } catch (SQLException e) {
                        System.out.println("No se pudo eliminar: " + e.getMessage());
                    }
                }
            }
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed

        NuevoProveedor nuevoProveedor = new NuevoProveedor();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevoProveedor)){
            escritorio.add(nuevoProveedor);
            nuevoProveedor.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevoProveedor);
        }        
    }//GEN-LAST:event_nuevoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarIdButton;
    private javax.swing.JTextField buscarIdTextField;
    private javax.swing.JTextField buscarNombreTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTodosButton;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JTable proveedoresTable;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
