/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Personal;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevoPersonal;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerPersonal;
import mx.gob.ceasonora.tonerManagement.implementaciones.PersonalImp;
import mx.gob.ceasonora.tonerManagement.interfaces.PersonalInt;

/**
 *
 * @author kevin
 */
public class AdministrarPersonal extends javax.swing.JInternalFrame {
    PersonalInt perImp = new PersonalImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Nombre", "Area", "Puesto"};
    List<Personal> listaPersonal;
    public static Personal personal;

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarPersonal() {
        initComponents();
        modelo = new DefaultTableModel();
        personalTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            listaPersonal = perImp.lista_personal();
            for(Personal per: listaPersonal){
                Object[] o = new Object[4];
                o[0] = per.getId();
                o[1] = per.getNombre();
                o[2] = per.getArea();
                o[3] = per.getPuesto();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        buscarNombreTextField = new javax.swing.JTextField();
        mostrarTodosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        personalTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Personal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Buscar por Nombre:");

        buscarNombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarNombreTextFieldKeyReleased(evt);
            }
        });

        mostrarTodosButton.setText("Mostrar Todos");
        mostrarTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mostrarTodosButton)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mostrarTodosButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        personalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Area", "Puesto"
            }
        ));
        jScrollPane1.setViewportView(personalTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevoButton.setText("Nuevo Personal");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver/Editar");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(verButton)
                .addGap(76, 76, 76)
                .addComponent(eliminarButton)
                .addGap(66, 66, 66)
                .addComponent(nuevoButton)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosButtonActionPerformed

        modelo = new DefaultTableModel();
        personalTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            listaPersonal = perImp.lista_personal();
            for(Personal per: listaPersonal){
                Object[] o = new Object[4];
                o[0] = per.getId();
                o[1] = per.getNombre();
                o[2] = per.getArea();
                o[3] = per.getPuesto();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_mostrarTodosButtonActionPerformed

    private void buscarNombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarNombreTextFieldKeyReleased

        modelo = new DefaultTableModel();
        personalTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            listaPersonal = perImp.buscar_nombre(buscarNombreTextField.getText());
            for(Personal per: listaPersonal){
                Object[] o = new Object[4];
                o[0] = per.getId();
                o[1] = per.getNombre();
                o[2] = per.getArea();
                o[3] = per.getPuesto();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarNombreTextFieldKeyReleased

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!personalTable.getSelectionModel().isSelectionEmpty()){
            personal = listaPersonal.get(personalTable.getSelectedRow());
            VerPersonal verPersonal = new VerPersonal();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verPersonal)){
                escritorio.add(verPersonal);
                verPersonal.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verPersonal);
            }
                   
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if(!personalTable.getSelectionModel().isSelectionEmpty()){
            personal = listaPersonal.get(personalTable.getSelectedRow());
            if(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el Personal "+personal.getNombre()+"?", "Eliminar Personal", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)==0){
                try {
                    if(perImp.Eliminar(personal)){
                        JOptionPane.showMessageDialog(null, "Personal eliminado con éxito", "Personal eliminado", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        personalTable.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        listaPersonal = perImp.lista_personal();
                        for(Personal per : listaPersonal){
                            Object[] o = new Object[4];
                            o[0] = per.getId();
                            o[1] = per.getNombre();
                            o[2] = per.getArea();
                            o[3] = per.getPuesto();

                            modelo.addRow(o);
                        }
                    }
                } catch (Exception e) {
                }
            }
        }
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed

        NuevoPersonal nuevoPersonal = new NuevoPersonal();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevoPersonal)){
            escritorio.add(nuevoPersonal);
            nuevoPersonal.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevoPersonal);
        }
        
    }//GEN-LAST:event_nuevoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarNombreTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTodosButton;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JTable personalTable;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
