/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Salida;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevaSalida;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerSalida;
import mx.gob.ceasonora.tonerManagement.implementaciones.SalidaImp;
import mx.gob.ceasonora.tonerManagement.instancias.InstanciaConexion;
import mx.gob.ceasonora.tonerManagement.interfaces.SalidaInt;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kevin
 */
public class AdministrarSalidas extends javax.swing.JInternalFrame {
    SalidaInt salImp = new SalidaImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Fecha", "Consumible", "Recibió"};
    List<Salida> salidas;
    public static Salida salida;

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarSalidas() {
        initComponents();
        modelo = new DefaultTableModel();
        salidasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            salidas = salImp.lista_salidas();
            for(Salida sal: salidas){
                Object[] o = new Object[4];
                o[0] = sal.getId();
                o[1] = sal.getFecha();
                o[2] = sal.getConsumible().getNombre();
                o[3] = sal.getPersonal().getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        idConsumibleTextField = new javax.swing.JTextField();
        buscarButton = new javax.swing.JButton();
        mostrarTextField = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        idPersonalTextField = new javax.swing.JTextField();
        buscarConsumibleButton = new javax.swing.JButton();
        buscarPersonalButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidasTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        reporteButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Salidas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Buscar por ID:");

        jLabel3.setText("Buscar por ID de Consumible:");

        idConsumibleTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idConsumibleTextFieldKeyReleased(evt);
            }
        });

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        mostrarTextField.setText("Mostrar Todos");
        mostrarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar por ID Personal:");

        buscarConsumibleButton.setText("Buscar");
        buscarConsumibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarConsumibleButtonActionPerformed(evt);
            }
        });

        buscarPersonalButton.setText("Buscar");
        buscarPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPersonalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(idConsumibleTextField)
                    .addComponent(idTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(idPersonalTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscarConsumibleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mostrarTextField)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarButton)
                            .addComponent(buscarPersonalButton))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idConsumibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarTextField)
                    .addComponent(buscarConsumibleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarPersonalButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        salidasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Fecha", "Consumible", "Recibió"
            }
        ));
        jScrollPane1.setViewportView(salidasTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevoButton.setText("Nueva Salida");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        reporteButton.setText("Recuperar Reporte");
        reporteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(reporteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(verButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevoButton)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton)
                    .addComponent(reporteButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTextFieldActionPerformed

        modelo = new DefaultTableModel();
        salidasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            salidas = salImp.lista_salidas();
            for(Salida sal: salidas){
                Object[] o = new Object[4];
                o[0] = sal.getId();
                o[1] = sal.getFecha();
                o[2] = sal.getConsumible().getNombre();
                o[3] = sal.getPersonal().getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_mostrarTextFieldActionPerformed

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed

        modelo = new DefaultTableModel();
        salidasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            salidas = salImp.buscar_id(Integer.parseInt(idTextField.getText()));
            for(Salida sal: salidas){
                Object[] o = new Object[4];
                o[0] = sal.getId();
                o[1] = sal.getFecha();
                o[2] = sal.getConsumible().getNombre();
                o[3] = sal.getPersonal().getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarButtonActionPerformed

    private void idConsumibleTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idConsumibleTextFieldKeyReleased
    }//GEN-LAST:event_idConsumibleTextFieldKeyReleased

    private void buscarConsumibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarConsumibleButtonActionPerformed

        modelo = new DefaultTableModel();
        salidasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            salidas = salImp.buscar_idConsumible(Integer.parseInt(idConsumibleTextField.getText()));
            for(Salida sal: salidas){
                Object[] o = new Object[4];
                o[0] = sal.getId();
                o[1] = sal.getFecha();
                o[2] = sal.getConsumible().getNombre();
                o[3] = sal.getPersonal().getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarConsumibleButtonActionPerformed

    private void buscarPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPersonalButtonActionPerformed

        modelo = new DefaultTableModel();
        salidasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            salidas = salImp.buscar_idPersonal(Integer.parseInt(idPersonalTextField.getText()));
            for(Salida sal: salidas){
                Object[] o = new Object[4];
                o[0] = sal.getId();
                o[1] = sal.getFecha();
                o[2] = sal.getConsumible().getNombre();
                o[3] = sal.getPersonal().getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarPersonalButtonActionPerformed

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!salidasTable.getSelectionModel().isSelectionEmpty()){
            salida = salidas.get(salidasTable.getSelectedRow());
            VerSalida verSalida = new VerSalida();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verSalida)){
                escritorio.add(verSalida);
                verSalida.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verSalida);
            }
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if(!salidasTable.getSelectionModel().isSelectionEmpty()){
            salida = salidas.get(salidasTable.getSelectedRow());
            if(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar la Salida "+salida.getId()+"?", "Eliminar Salida", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)==0){
                try {
                    if(salImp.Eliminar(salida)){
                        JOptionPane.showMessageDialog(null, "Salida eliminada con éxito", "Salida eliminada", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        salidasTable.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        salidas = salImp.lista_salidas();
                        for(Salida sal : salidas){
                            Object[] o = new Object[4];
                            o[0] = sal.getId();
                            o[1] = sal.getFecha();
                            o[2] = sal.getConsumible().getNombre();
                            o[3] = sal.getPersonal().getNombre();
                            
                            modelo.addRow(o);
                        }
                    }
                } catch (SQLException e) {
                    System.out.println("No se pudo eliminar: "+e.getSQLState());
                }
            }
        }
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed

        NuevaSalida nuevaSalida = new NuevaSalida();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevaSalida)){
            escritorio.add(nuevaSalida);
            nuevaSalida.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevaSalida);
        }
        
    }//GEN-LAST:event_nuevoButtonActionPerformed

    private void reporteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteButtonActionPerformed

        try {
            salida = salidas.get(salidasTable.getSelectedRow());
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("idSalida", salida.getId());

                InstanciaConexion conexion = InstanciaConexion.getInstanciaConexion();
                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_reporteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JButton buscarConsumibleButton;
    private javax.swing.JButton buscarPersonalButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTextField idConsumibleTextField;
    private javax.swing.JTextField idPersonalTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTextField;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JButton reporteButton;
    private javax.swing.JTable salidasTable;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
