/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Consumible;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevoConsumible;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerConsumible;
import mx.gob.ceasonora.tonerManagement.implementaciones.ConsumibleImp;
import mx.gob.ceasonora.tonerManagement.interfaces.ConsumibleInt;

/**
 *
 * @author kevin
 */
public class AdministrarConsumibles extends javax.swing.JInternalFrame {
    ConsumibleInt conImp = new ConsumibleImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "# Producto", "Nombre", "Cantidad"};
    List<Consumible> consumibles;
    public static Consumible consumible;

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarConsumibles() {
        initComponents();
        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            consumibles = conImp.lista_consumibles();
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarIdTextField = new javax.swing.JTextField();
        buscarNombreTextField = new javax.swing.JTextField();
        buscarIdButton = new javax.swing.JButton();
        mostrarTodosButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buscarCodigoTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        consumiblesTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Consumibles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Buscar por ID:");

        jLabel3.setText("Buscar por Nombre:");

        buscarNombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarNombreTextFieldKeyReleased(evt);
            }
        });

        buscarIdButton.setText("Buscar");
        buscarIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdButtonActionPerformed(evt);
            }
        });

        mostrarTodosButton.setText("Mostrar Todos");
        mostrarTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar por # Producto:");

        buscarCodigoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarCodigoTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarIdButton))
                            .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mostrarTodosButton)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarIdButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mostrarTodosButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buscarCodigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        consumiblesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "# Producto", "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(consumiblesTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevoButton.setText("Nuevo Consumible");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver/Editar");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(verButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(eliminarButton)
                .addGap(61, 61, 61)
                .addComponent(nuevoButton)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosButtonActionPerformed

        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            consumibles = conImp.lista_consumibles();
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_mostrarTodosButtonActionPerformed

    private void buscarNombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarNombreTextFieldKeyReleased

        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            consumibles = conImp.buscar_nombre(buscarNombreTextField.getText());
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarNombreTextFieldKeyReleased

    private void buscarCodigoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarCodigoTextFieldKeyReleased

        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            consumibles = conImp.buscar_codigo(buscarCodigoTextField.getText());
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarCodigoTextFieldKeyReleased

    private void buscarIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdButtonActionPerformed

        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            consumibles = conImp.buscar_id(Integer.parseInt(buscarIdTextField.getText()));
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarIdButtonActionPerformed

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!consumiblesTable.getSelectionModel().isSelectionEmpty()){
            consumible = consumibles.get(consumiblesTable.getSelectedRow());
            VerConsumible verConsumible = new VerConsumible();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verConsumible)){
                escritorio.add(verConsumible);
                verConsumible.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verConsumible);
            }
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if (!consumiblesTable.getSelectionModel().isSelectionEmpty()) {
            consumible = consumibles.get(consumiblesTable.getSelectedRow());
            if (JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el Consumible " + consumible.getNombre() + "?", "Eliminar Consumible", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0) {
                try {
                    if (conImp.Eliminar(consumible)) {
                        JOptionPane.showMessageDialog(null, "Consumible eliminado con éxito.", "Consumible eliminado", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        consumiblesTable.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        consumibles = conImp.lista_consumibles();
                        for (Consumible con : consumibles) {
                            Object[] o = new Object[4];
                            o[0] = con.getId();
                            o[1] = con.getCodigoProducto();
                            o[2] = con.getNombre();
                            o[3] = con.getCantidad();

                            modelo.addRow(o);
                        }
                    }
                } catch (Exception e) {
                    System.out.println("No se pudo eliminar");
                }
            }
        }

    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed

        NuevoConsumible nuevoConsumible = new NuevoConsumible();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevoConsumible)){
            escritorio.add(nuevoConsumible);
            nuevoConsumible.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevoConsumible);
        }
        
    }//GEN-LAST:event_nuevoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarCodigoTextField;
    private javax.swing.JButton buscarIdButton;
    private javax.swing.JTextField buscarIdTextField;
    private javax.swing.JTextField buscarNombreTextField;
    private javax.swing.JTable consumiblesTable;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTodosButton;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
