/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Usuario;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevoUsuario;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerUsuario;
import mx.gob.ceasonora.tonerManagement.implementaciones.UsuarioImp;
import mx.gob.ceasonora.tonerManagement.interfaces.UsuarioInt;

/**
 *
 * @author kevin
 */
public class AdministrarUsuarios extends javax.swing.JInternalFrame {
    UsuarioInt usrImp = new UsuarioImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "Correo", "Nombre de Usuario", "Nombre"};
    List<Usuario> usuarios;
    public static Usuario usuario;

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarUsuarios() {
        initComponents();
        modelo = new DefaultTableModel();
        usuariosTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            usuarios = usrImp.lista_usuarios();
            for(Usuario usr: usuarios){
                Object[] o = new Object[4];
                o[0] = usr.getId();
                o[1] = usr.getCorreo();
                o[2] = usr.getNombreUsuario();
                o[3] = usr.getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarCorreoTextField = new javax.swing.JTextField();
        buscarNombreTextField = new javax.swing.JTextField();
        mostrarTodosButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usuariosTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevoButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Buscar por Correo:");

        jLabel3.setText("Buscar por Nombre:");

        buscarCorreoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarCorreoTextFieldKeyReleased(evt);
            }
        });

        buscarNombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarNombreTextFieldKeyReleased(evt);
            }
        });

        mostrarTodosButton.setText("Mostrar Todos");
        mostrarTodosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarNombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(buscarCorreoTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(mostrarTodosButton)
                .addGap(84, 84, 84))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(buscarCorreoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(mostrarTodosButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuariosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Correo", "Nombre de Usuario", "Nombre"
            }
        ));
        jScrollPane1.setViewportView(usuariosTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevoButton.setText("Nuevo Usuario");
        nuevoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver/Editar");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(verButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(eliminarButton)
                .addGap(61, 61, 61)
                .addComponent(nuevoButton)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosButtonActionPerformed

        modelo = new DefaultTableModel();
        usuariosTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            usuarios = usrImp.lista_usuarios();
            for(Usuario usr: usuarios){
                Object[] o = new Object[4];
                o[0] = usr.getId();
                o[1] = usr.getCorreo();
                o[2] = usr.getNombreUsuario();
                o[3] = usr.getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_mostrarTodosButtonActionPerformed

    private void buscarCorreoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarCorreoTextFieldKeyReleased

        modelo = new DefaultTableModel();
        usuariosTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            usuarios = usrImp.buscar_correo(buscarCorreoTextField.getText());
            for(Usuario usr: usuarios){
                Object[] o = new Object[4];
                o[0] = usr.getId();
                o[1] = usr.getCorreo();
                o[2] = usr.getNombreUsuario();
                o[3] = usr.getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarCorreoTextFieldKeyReleased

    private void buscarNombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarNombreTextFieldKeyReleased

        modelo = new DefaultTableModel();
        usuariosTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            usuarios = usrImp.buscar_nombre(buscarNombreTextField.getText());
            for(Usuario usr: usuarios){
                Object[] o = new Object[4];
                o[0] = usr.getId();
                o[1] = usr.getCorreo();
                o[2] = usr.getNombreUsuario();
                o[3] = usr.getNombre();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarNombreTextFieldKeyReleased

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!usuariosTable.getSelectionModel().isSelectionEmpty()){
            usuario = usuarios.get(usuariosTable.getSelectedRow());
            VerUsuario verUsuario = new VerUsuario();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verUsuario)){
                escritorio.add(verUsuario);
                verUsuario.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verUsuario);
            }
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if(!usuariosTable.getSelectionModel().isSelectionEmpty()){
            usuario = usuarios.get(usuariosTable.getSelectedRow());
            if(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar el Usuario "+usuario.getNombreUsuario(), "Eliminar Usuario", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)==0){
                try {
                    if (usrImp.Eliminar(usuario)) {
                        JOptionPane.showMessageDialog(null, "Usuario eliminado con éxito", "Usuario eliminado", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        usuariosTable.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        usuarios = usrImp.lista_usuarios();
                        for (Usuario usr : usuarios) {
                            Object[] o = new Object[4];
                            o[0] = usr.getId();
                            o[1] = usr.getCorreo();
                            o[2] = usr.getNombreUsuario();
                            o[3] = usr.getNombre();

                            modelo.addRow(o);
                        }

                    }
                } catch (Exception e) {
                }
            }
        }
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoButtonActionPerformed

        NuevoUsuario nuevoUsuario = new NuevoUsuario();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevoUsuario)){
            escritorio.add(nuevoUsuario);
            nuevoUsuario.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevoUsuario);
        }
        
    }//GEN-LAST:event_nuevoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarCorreoTextField;
    private javax.swing.JTextField buscarNombreTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTodosButton;
    private javax.swing.JButton nuevoButton;
    private javax.swing.JTable usuariosTable;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
