/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Herramienta;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevaHerramienta;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerHerramienta;
import mx.gob.ceasonora.tonerManagement.implementaciones.HerramientaImp;
import mx.gob.ceasonora.tonerManagement.interfaces.HerramientaInt;

/**
 *
 * @author kevin
 */
public class AdministrarHerramientas extends javax.swing.JInternalFrame {
    HerramientaInt herImp = new HerramientaImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "# Producto", "Nombre", "Cantidad Total", "Cantidad Disponible"};
    List<Herramienta> herramientas;
    public static Herramienta herramienta;

    /**
     * Creates new form AdministrarHerramientas
     */
    public AdministrarHerramientas() {
        initComponents();
        modelo = new DefaultTableModel();
        herramientasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            herramientas = herImp.lista_herramientas();
            for(Herramienta her: herramientas){
                Object[] o = new Object[5];
                o[0] = her.getId();
                o[1] = her.getCodigoProducto();
                o[2] = her.getNombre();
                o[3] = her.getCantidadTotal();
                o[4] = her.getCantidadDisponible();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buscarIdTextField = new javax.swing.JTextField();
        buscarNombreTextField = new javax.swing.JTextField();
        buscarIdButton = new javax.swing.JButton();
        mostrarTodasButton = new javax.swing.JButton();
        buscarCodigoProductoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        herramientasTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        nuevaHerramientaButton = new javax.swing.JButton();
        verButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Administrar Herramientas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Buscar por ID:");

        jLabel3.setText("Buscar por Nombre:");

        buscarNombreTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarNombreTextFieldKeyReleased(evt);
            }
        });

        buscarIdButton.setText("Buscar");
        buscarIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIdButtonActionPerformed(evt);
            }
        });

        mostrarTodasButton.setText("Mostrar Todas");
        mostrarTodasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodasButtonActionPerformed(evt);
            }
        });

        buscarCodigoProductoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarCodigoProductoTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setText("Buscar por # Producto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCodigoProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarIdButton)))
                .addGap(77, 77, 77)
                .addComponent(mostrarTodasButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(buscarIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarIdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(buscarNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarTodasButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(buscarCodigoProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        herramientasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "# Producto", "Nombre", "Cantidad Total", "Cantidad Disponible"
            }
        ));
        jScrollPane1.setViewportView(herramientasTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        nuevaHerramientaButton.setText("Nueva Herramienta");
        nuevaHerramientaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaHerramientaButtonActionPerformed(evt);
            }
        });

        verButton.setText("Ver/Editar");
        verButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verButtonActionPerformed(evt);
            }
        });

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(verButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(eliminarButton)
                .addGap(61, 61, 61)
                .addComponent(nuevaHerramientaButton)
                .addGap(64, 64, 64))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevaHerramientaButton)
                    .addComponent(verButton)
                    .addComponent(eliminarButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTodasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodasButtonActionPerformed

        modelo = new DefaultTableModel();
        herramientasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            herramientas = herImp.lista_herramientas();
            for(Herramienta her: herramientas){
                Object[] o = new Object[5];
                o[0] = her.getId();
                o[1] = her.getCodigoProducto();
                o[2] = her.getNombre();
                o[3] = her.getCantidadTotal();
                o[4] = her.getCantidadDisponible();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_mostrarTodasButtonActionPerformed

    private void buscarIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIdButtonActionPerformed

        modelo = new DefaultTableModel();
        herramientasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            herramientas = herImp.buscar_id(Integer.parseInt(buscarIdTextField.getText()));
            for(Herramienta her: herramientas){
                Object[] o = new Object[5];
                o[0] = her.getId();
                o[1] = her.getCodigoProducto();
                o[2] = her.getNombre();
                o[3] = her.getCantidadTotal();
                o[4] = her.getCantidadDisponible();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarIdButtonActionPerformed

    private void buscarNombreTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarNombreTextFieldKeyReleased

        modelo = new DefaultTableModel();
        herramientasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            herramientas = herImp.buscar_nombre(buscarNombreTextField.getText());
            for(Herramienta her: herramientas){
                Object[] o = new Object[5];
                o[0] = her.getId();
                o[1] = her.getCodigoProducto();
                o[2] = her.getNombre();
                o[3] = her.getCantidadTotal();
                o[4] = her.getCantidadDisponible();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarNombreTextFieldKeyReleased

    private void buscarCodigoProductoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarCodigoProductoTextFieldKeyReleased

        modelo = new DefaultTableModel();
        herramientasTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            herramientas = herImp.buscar_codigo(buscarCodigoProductoTextField.getText());
            for(Herramienta her: herramientas){
                Object[] o = new Object[5];
                o[0] = her.getId();
                o[1] = her.getCodigoProducto();
                o[2] = her.getNombre();
                o[3] = her.getCantidadTotal();
                o[4] = her.getCantidadDisponible();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
        
    }//GEN-LAST:event_buscarCodigoProductoTextFieldKeyReleased

    private void verButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verButtonActionPerformed

        if(!herramientasTable.getSelectionModel().isSelectionEmpty()){
            herramienta = herramientas.get(herramientasTable.getSelectedRow());
            VerHerramienta verHerramienta = new VerHerramienta();
            JDesktopPane escritorio = getDesktopPane();
            if(!escritorio.isAncestorOf(verHerramienta)){
                escritorio.add(verHerramienta);
                verHerramienta.setVisible(true);
            }else{
                escritorio.setSelectedFrame(verHerramienta);
            }
        }
        
    }//GEN-LAST:event_verButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        if(!herramientasTable.getSelectionModel().isSelectionEmpty()){
            herramienta = herramientas.get(herramientasTable.getSelectedRow());
            if(JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea eliminar la Herramienta "+herramienta.getNombre()+"?", "Eliminar Herramienta", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE)==0){
                try{
                    if(herImp.Eliminar(herramienta)){
                        JOptionPane.showMessageDialog(null, "Herramienta eliminada con éxito.", "Herramienta eliminada", JOptionPane.INFORMATION_MESSAGE);
                        modelo = new DefaultTableModel();
                        herramientasTable.setModel(modelo);
                        modelo.setColumnIdentifiers(titulos);
                        herramientas = herImp.lista_herramientas();
                        for(Herramienta her: herramientas){
                            Object[] o = new Object[5];
                            o[0] = her.getId();
                            o[1] = her.getCodigoProducto();
                            o[2] = her.getNombre();
                            o[3] = her.getCantidadTotal();
                            o[4] = her.getCantidadDisponible();
                            
                            modelo.addRow(o);
                        }
                    }
                }catch(Exception e){
                    System.out.println("No se pudo eliminar");
                }
            }
        }
        
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void nuevaHerramientaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaHerramientaButtonActionPerformed

        NuevaHerramienta nuevaHerramienta = new NuevaHerramienta();
        JDesktopPane escritorio = getDesktopPane();
        if(!escritorio.isAncestorOf(nuevaHerramienta)){
            escritorio.add(nuevaHerramienta);
            nuevaHerramienta.setVisible(true);
        }else{
            escritorio.setSelectedFrame(nuevaHerramienta);
        }
        
    }//GEN-LAST:event_nuevaHerramientaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarCodigoProductoTextField;
    private javax.swing.JButton buscarIdButton;
    private javax.swing.JTextField buscarIdTextField;
    private javax.swing.JTextField buscarNombreTextField;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JTable herramientasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarTodasButton;
    private javax.swing.JButton nuevaHerramientaButton;
    private javax.swing.JButton verButton;
    // End of variables declaration//GEN-END:variables
}
