/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.reporte;

import java.util.HashMap;
import java.util.List;
import javax.swing.JDialog;
import mx.gob.ceasonora.tonerManagement.entidades.Prestamo;
import mx.gob.ceasonora.tonerManagement.gui.administrar.AdministrarSalidas;
import mx.gob.ceasonora.tonerManagement.instancias.InstanciaConexion;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;



/**
 *
 * @author kevin
 */
public class GenerarReporte extends javax.swing.JInternalFrame {
    InstanciaConexion conexion = InstanciaConexion.getInstanciaConexion();
    
    

    /**
     * Creates new form AdministrarHerramientas
     */
    public GenerarReporte() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrarGroup = new javax.swing.ButtonGroup();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        reporteSalidasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        salida_fechaDateChooser = new com.toedter.calendar.JDateChooser();
        salida_generarFechaButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        salida_criterioFechaComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salida_idConsumibleTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        salida_codigoProductoTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        salida_criterioConsumibleComboBox = new javax.swing.JComboBox<>();
        salida_generarConsumibleButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        salida_idPersonalTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        salida_telefonoPersonalTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        salida_criterioPersonalComboBox = new javax.swing.JComboBox<>();
        salida_generarPersonalButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        salida_idSalidaTextField = new javax.swing.JTextField();
        salida_generarSalidaButton = new javax.swing.JButton();
        salida_administrarButton = new javax.swing.JButton();
        reportePrestamosPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        prestamo_idPrestamoTextField = new javax.swing.JTextField();
        prestamo_generarPrestamoButton = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        prestamo_idDevolucionTextField = new javax.swing.JTextField();
        prestamo_generarDevolucionButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        reporteConsumiblesPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        consumible_tipoComboBox = new javax.swing.JComboBox<>();
        consumible_generarButton = new javax.swing.JButton();
        reporteHerramientasPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        herramienta_tipoComboBox = new javax.swing.JComboBox<>();
        herramienta_generarButton = new javax.swing.JButton();

        setClosable(true);

        jPanel8.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Por Día/Mes/Año:");

        salida_generarFechaButton.setText("Generar Reporte");
        salida_generarFechaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_generarFechaButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha:");

        jLabel7.setText("Criterio:");

        salida_criterioFechaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por Día", "Por Mes", "Por Año" }));
        salida_criterioFechaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_criterioFechaComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Por Consumible:");

        jLabel5.setText("ID: ");

        jLabel6.setText("# Producto:");

        jLabel8.setText("Criterio:");

        salida_criterioConsumibleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por ID", "Por # Producto" }));

        salida_generarConsumibleButton.setText("Generar Reporte");
        salida_generarConsumibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_generarConsumibleButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Por Personal:");

        jLabel10.setText("ID: ");

        jLabel11.setText("Teléfono: ");

        jLabel12.setText("Criterio:");

        salida_criterioPersonalComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por ID", "Por Teléfono" }));

        salida_generarPersonalButton.setText("Generar Reporte");
        salida_generarPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_generarPersonalButtonActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Recuperar Reporte de Salida:");

        jLabel14.setText("ID: ");

        salida_generarSalidaButton.setText("Generar Reporte");
        salida_generarSalidaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_generarSalidaButtonActionPerformed(evt);
            }
        });

        salida_administrarButton.setText("Administrar Salidas");
        salida_administrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salida_administrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reporteSalidasPanelLayout = new javax.swing.GroupLayout(reporteSalidasPanel);
        reporteSalidasPanel.setLayout(reporteSalidasPanelLayout);
        reporteSalidasPanelLayout.setHorizontalGroup(
            reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salida_idConsumibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salida_codigoProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salida_criterioConsumibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salida_generarConsumibleButton))
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addGap(0, 59, Short.MAX_VALUE))
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reporteSalidasPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salida_idPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salida_telefonoPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salida_criterioPersonalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salida_generarPersonalButton)
                .addGap(58, 58, 58))
            .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salida_fechaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salida_criterioFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salida_generarFechaButton))
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13))
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salida_idSalidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salida_generarSalidaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(salida_administrarButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reporteSalidasPanelLayout.setVerticalGroup(
            reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reporteSalidasPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salida_fechaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(salida_generarFechaButton)
                        .addComponent(jLabel7)
                        .addComponent(salida_criterioFechaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(salida_idConsumibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(salida_codigoProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(salida_criterioConsumibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salida_generarConsumibleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(salida_idPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(salida_telefonoPersonalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(salida_criterioPersonalComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salida_generarPersonalButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reporteSalidasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(salida_idSalidaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salida_generarSalidaButton)
                    .addComponent(salida_administrarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salidas", reporteSalidasPanel);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Recuperar Reporte de Préstamo:");

        jLabel18.setText("ID: ");

        prestamo_generarPrestamoButton.setText("Generar Reporte");
        prestamo_generarPrestamoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamo_generarPrestamoButtonActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Recuperar Reporte de Devolución:");

        jLabel20.setText("ID: ");

        prestamo_generarDevolucionButton.setText("Generar Reporte");
        prestamo_generarDevolucionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prestamo_generarDevolucionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportePrestamosPanelLayout = new javax.swing.GroupLayout(reportePrestamosPanel);
        reportePrestamosPanel.setLayout(reportePrestamosPanelLayout);
        reportePrestamosPanelLayout.setHorizontalGroup(
            reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prestamo_idPrestamoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prestamo_generarPrestamoButton))
                            .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prestamo_idDevolucionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prestamo_generarDevolucionButton)))))
                .addContainerGap(346, Short.MAX_VALUE))
            .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                .addComponent(jSeparator4)
                .addContainerGap())
        );
        reportePrestamosPanelLayout.setVerticalGroup(
            reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportePrestamosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(prestamo_idPrestamoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prestamo_generarPrestamoButton))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(reportePrestamosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(prestamo_idDevolucionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prestamo_generarDevolucionButton))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Préstamos", reportePrestamosPanel);

        jLabel15.setText("Tipo de Reporte: ");

        consumible_tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listado de Consumibles", "Listado de Faltantes", "Listado de Escasos" }));

        consumible_generarButton.setText("Generar Reporte");
        consumible_generarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consumible_generarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reporteConsumiblesPanelLayout = new javax.swing.GroupLayout(reporteConsumiblesPanel);
        reporteConsumiblesPanel.setLayout(reporteConsumiblesPanelLayout);
        reporteConsumiblesPanelLayout.setHorizontalGroup(
            reporteConsumiblesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteConsumiblesPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(reporteConsumiblesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consumible_generarButton)
                    .addGroup(reporteConsumiblesPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consumible_tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        reporteConsumiblesPanelLayout.setVerticalGroup(
            reporteConsumiblesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteConsumiblesPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(reporteConsumiblesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(consumible_tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consumible_generarButton)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consumibles", reporteConsumiblesPanel);

        jLabel16.setText("Tipo de Reporte: ");

        herramienta_tipoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Listado de Herramientas", "Herramientas Faltantes", "Herramientas Escasas" }));

        herramienta_generarButton.setText("Generar Reporte");
        herramienta_generarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                herramienta_generarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reporteHerramientasPanelLayout = new javax.swing.GroupLayout(reporteHerramientasPanel);
        reporteHerramientasPanel.setLayout(reporteHerramientasPanelLayout);
        reporteHerramientasPanelLayout.setHorizontalGroup(
            reporteHerramientasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteHerramientasPanelLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(reporteHerramientasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(herramienta_generarButton)
                    .addGroup(reporteHerramientasPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(herramienta_tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        reporteHerramientasPanelLayout.setVerticalGroup(
            reporteHerramientasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reporteHerramientasPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(reporteHerramientasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(herramienta_tipoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(herramienta_generarButton)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Herramientas", reporteHerramientasPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salida_criterioFechaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_criterioFechaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salida_criterioFechaComboBoxActionPerformed

    private void salida_generarFechaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_generarFechaButtonActionPerformed

        switch (salida_criterioFechaComboBox.getSelectedIndex()) {
            case 0:
            try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("fecha", salida_fechaDateChooser.getDate());

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_dia.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
            break;

            case 1:
            try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("fecha", salida_fechaDateChooser.getDate());

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_mes.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
            break;

            case 2:
            try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("fecha", salida_fechaDateChooser.getDate());

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_ano.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
            break;
        }
    }//GEN-LAST:event_salida_generarFechaButtonActionPerformed

    private void salida_generarConsumibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_generarConsumibleButtonActionPerformed

        switch(salida_criterioConsumibleComboBox.getSelectedIndex()){
            case 0:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("idConsumible", Integer.parseInt(salida_idConsumibleTextField.getText()));

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_idConsumible.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 1:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("codigoProducto", salida_codigoProductoTextField.getText());

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_codigoProducto.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
        }
        
    }//GEN-LAST:event_salida_generarConsumibleButtonActionPerformed

    private void salida_generarSalidaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_generarSalidaButtonActionPerformed

        try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("idSalida", Integer.parseInt(salida_idSalidaTextField.getText()));

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_salida_generarSalidaButtonActionPerformed

    private void salida_administrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_administrarButtonActionPerformed

        AdministrarSalidas salidas = new AdministrarSalidas();
        getDesktopPane().add(salidas);
        salidas.setVisible(true);
        
    }//GEN-LAST:event_salida_administrarButtonActionPerformed

    private void salida_generarPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salida_generarPersonalButtonActionPerformed

        switch(salida_criterioPersonalComboBox.getSelectedIndex()){
            case 0:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("idPersonal", Integer.parseInt(salida_idPersonalTextField.getText()));

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_idPersonal.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 1:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);

                HashMap parametros = new HashMap();

                parametros.put("telefono", salida_telefonoPersonalTextField.getText());

                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_salida_telefonoPersonal.jasper", parametros, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
        }
        
    }//GEN-LAST:event_salida_generarPersonalButtonActionPerformed

    private void consumible_generarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consumible_generarButtonActionPerformed

        switch(consumible_tipoComboBox.getSelectedIndex()){
            case 0:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_consumibles.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 1:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_consumible_faltantes.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 2:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_consumible_escasos.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
        }
        
    }//GEN-LAST:event_consumible_generarButtonActionPerformed

    private void herramienta_generarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herramienta_generarButtonActionPerformed

        switch(herramienta_tipoComboBox.getSelectedIndex()){
            case 0:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_herramientas.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 1:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_herramienta_faltantes.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
                
            case 2:
                try {
                JDialog espera = new JDialog();
                espera.setLocationRelativeTo(null);
                espera.setTitle("Generando reporte...");
                espera.pack();
                espera.setVisible(true);


                conexion.conexion();
                JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_herramienta_escasos.jasper", null, conexion.con);
                JasperViewer.viewReport(jp, false);
                espera.setVisible(false);

            } catch (Exception e) {
                e.printStackTrace();
            }
                break;
        }
        
    }//GEN-LAST:event_herramienta_generarButtonActionPerformed

    private void prestamo_generarPrestamoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamo_generarPrestamoButtonActionPerformed

        try {
            JDialog espera = new JDialog();
            espera.setLocationRelativeTo(null);
            espera.setTitle("Generando reporte...");
            espera.pack();
            espera.setVisible(true);

            HashMap parametros = new HashMap();
            parametros.put("idPrestamo", Integer.parseInt(prestamo_idPrestamoTextField.getText()));

            conexion.conexion();
            JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_prestamo.jasper", parametros, conexion.con);
            JasperViewer.viewReport(jp, false);
            espera.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_prestamo_generarPrestamoButtonActionPerformed

    private void prestamo_generarDevolucionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prestamo_generarDevolucionButtonActionPerformed

        try {
            JDialog espera = new JDialog();
            espera.setLocationRelativeTo(null);
            espera.setTitle("Generando reporte...");
            espera.pack();
            espera.setVisible(true);

            HashMap parametros = new HashMap();
            parametros.put("idPrestamo", Integer.parseInt(prestamo_idDevolucionTextField.getText()));

            conexion.conexion();
            JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_devolucion.jasper", parametros, conexion.con);
            JasperViewer.viewReport(jp, false);
            espera.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_prestamo_generarDevolucionButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consumible_generarButton;
    private javax.swing.JComboBox<String> consumible_tipoComboBox;
    private javax.swing.JButton herramienta_generarButton;
    private javax.swing.JComboBox<String> herramienta_tipoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.ButtonGroup mostrarGroup;
    private javax.swing.JButton prestamo_generarDevolucionButton;
    private javax.swing.JButton prestamo_generarPrestamoButton;
    private javax.swing.JTextField prestamo_idDevolucionTextField;
    private javax.swing.JTextField prestamo_idPrestamoTextField;
    private javax.swing.JPanel reporteConsumiblesPanel;
    private javax.swing.JPanel reporteHerramientasPanel;
    private javax.swing.JPanel reportePrestamosPanel;
    private javax.swing.JPanel reporteSalidasPanel;
    private javax.swing.JButton salida_administrarButton;
    private javax.swing.JTextField salida_codigoProductoTextField;
    private javax.swing.JComboBox<String> salida_criterioConsumibleComboBox;
    private javax.swing.JComboBox<String> salida_criterioFechaComboBox;
    private javax.swing.JComboBox<String> salida_criterioPersonalComboBox;
    private com.toedter.calendar.JDateChooser salida_fechaDateChooser;
    private javax.swing.JButton salida_generarConsumibleButton;
    private javax.swing.JButton salida_generarFechaButton;
    private javax.swing.JButton salida_generarPersonalButton;
    private javax.swing.JButton salida_generarSalidaButton;
    private javax.swing.JTextField salida_idConsumibleTextField;
    private javax.swing.JTextField salida_idPersonalTextField;
    private javax.swing.JTextField salida_idSalidaTextField;
    private javax.swing.JTextField salida_telefonoPersonalTextField;
    // End of variables declaration//GEN-END:variables
}
