/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui.administrar.ver;

import javax.swing.JOptionPane;
import mx.gob.ceasonora.tonerManagement.entidades.Herramienta;
import mx.gob.ceasonora.tonerManagement.gui.administrar.AdministrarHerramientas;
import mx.gob.ceasonora.tonerManagement.implementaciones.HerramientaImp;
import mx.gob.ceasonora.tonerManagement.interfaces.HerramientaInt;


/**
 *
 * @author kevin
 */
public class VerHerramienta extends javax.swing.JInternalFrame {
    Herramienta herramienta;
    int cantidadTotal;

    /**
     * Creates new form NuevoConsumible
     */
    public VerHerramienta() {
        
        initComponents();
        herramienta = AdministrarHerramientas.herramienta;
        idTextField.setText(String.valueOf(herramienta.getId()));
        codigoProductoTextField.setText(herramienta.getCodigoProducto());
        nombreTextField.setText(herramienta.getNombre());
        descripcionTextField.setText(herramienta.getDescripcion());
        cantidadTotalTextField.setText(String.valueOf(herramienta.getCantidadTotal()));
        cantidadDisponibleTextField.setText(String.valueOf(herramienta.getCantidadDisponible()));
        precioUnitarioTextField.setText(String.valueOf(herramienta.getPrecioUnitario()));
        cantidadTotal = herramienta.getCantidadTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codigoProductoTextField = new javax.swing.JTextField();
        cantidadTotalTextField = new javax.swing.JTextField();
        cantidadDisponibleTextField = new javax.swing.JTextField();
        guardarButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        descripcionTextField = new javax.swing.JTextField();
        precioUnitarioTextField = new javax.swing.JTextField();
        editarButton = new javax.swing.JButton();
        editarCantidadTotalButton = new javax.swing.JButton();
        editarCantidadDisponibleButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ver/Editar Herramienta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("Numero de Producto:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Descripcion:");

        jLabel8.setText("Cantidad Total:");

        jLabel9.setText("Cantidad Disponible:");

        codigoProductoTextField.setEnabled(false);

        cantidadTotalTextField.setEnabled(false);
        cantidadTotalTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadTotalTextFieldKeyReleased(evt);
            }
        });

        cantidadDisponibleTextField.setEnabled(false);

        guardarButton.setText("Guardar Cambios");
        guardarButton.setEnabled(false);
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio Unitario:");

        nombreTextField.setEnabled(false);

        descripcionTextField.setEnabled(false);

        precioUnitarioTextField.setEnabled(false);

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        editarCantidadTotalButton.setText("Editar");
        editarCantidadTotalButton.setEnabled(false);
        editarCantidadTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCantidadTotalButtonActionPerformed(evt);
            }
        });

        editarCantidadDisponibleButton.setText("Editar");
        editarCantidadDisponibleButton.setEnabled(false);
        editarCantidadDisponibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCantidadDisponibleButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        idTextField.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(editarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guardarButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codigoProductoTextField)
                            .addComponent(descripcionTextField)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idTextField))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadTotalTextField)
                                    .addComponent(cantidadDisponibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarCantidadTotalButton)
                                    .addComponent(editarCantidadDisponibleButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precioUnitarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(codigoProductoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(cantidadTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editarCantidadTotalButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cantidadDisponibleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editarCantidadDisponibleButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(descripcionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(precioUnitarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(editarButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed

        try {
            herramienta.setCantidadTotal(Integer.parseInt(cantidadTotalTextField.getText()));
            herramienta.setCantidadDisponible(Integer.parseInt(cantidadDisponibleTextField.getText()));
            herramienta.setNombre(nombreTextField.getText());
            herramienta.setPrecioUnitario(Double.parseDouble(precioUnitarioTextField.getText()));
            herramienta.setDescripcion(descripcionTextField.getText());
            herramienta.setCodigoProducto(codigoProductoTextField.getText());
            HerramientaInt herImp = new HerramientaImp();
            if(herImp.Editar(herramienta, herramienta)){
                JOptionPane.showMessageDialog(null, "Datos acutalizados con éxito.", "Cambios guardados", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }

        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed

        codigoProductoTextField.setEnabled(true);
        nombreTextField.setEnabled(true);
        precioUnitarioTextField.setEnabled(true);
        descripcionTextField.setEnabled(true);
        guardarButton.setEnabled(true);
        editarCantidadTotalButton.setEnabled(true);
        editarCantidadDisponibleButton.setEnabled(true);
        
    }//GEN-LAST:event_editarButtonActionPerformed

    private void editarCantidadTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCantidadTotalButtonActionPerformed

        JOptionPane.showMessageDialog(null, "No se recomienda editar Cantidad Total ni Cantidad Disponible si esta herramienta cuenta con un préstamo.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        cantidadTotalTextField.setEnabled(true);
        
    }//GEN-LAST:event_editarCantidadTotalButtonActionPerformed

    private void editarCantidadDisponibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCantidadDisponibleButtonActionPerformed

        JOptionPane.showMessageDialog(null, "No se recomienda editar Cantidad Total ni Cantidad Disponible si esta herramienta cuenta con un préstamo.", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        cantidadDisponibleTextField.setEnabled(true);
        
    }//GEN-LAST:event_editarCantidadDisponibleButtonActionPerformed

    private void cantidadTotalTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTotalTextFieldKeyReleased

        if(cantidadTotalTextField.getText().equals("")){
            cantidadTotalTextField.setText("0");
        }
        if(cantidadTotalTextField.getText().startsWith("0")&&cantidadTotalTextField.getText().length()>1){
            cantidadTotalTextField.setText(cantidadTotalTextField.getText().substring(1, cantidadTotalTextField.getText().length()));
        }
        int cantidadTotalNueva = Integer.parseInt(cantidadTotalTextField.getText());
        int sumar = cantidadTotalNueva-cantidadTotal;
        cantidadTotal = cantidadTotalNueva;
        int cantidadDisponible = Integer.parseInt(cantidadDisponibleTextField.getText());
        int cantidadDisponibleNueva = cantidadDisponible + sumar;
        cantidadDisponible = cantidadDisponibleNueva;
        cantidadDisponibleTextField.setText(String.valueOf(cantidadDisponibleNueva));
        
    }//GEN-LAST:event_cantidadTotalTextFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidadDisponibleTextField;
    private javax.swing.JTextField cantidadTotalTextField;
    private javax.swing.JTextField codigoProductoTextField;
    private javax.swing.JTextField descripcionTextField;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton editarCantidadDisponibleButton;
    private javax.swing.JButton editarCantidadTotalButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField precioUnitarioTextField;
    // End of variables declaration//GEN-END:variables
}
