/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.gob.ceasonora.tonerManagement.gui;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.gob.ceasonora.tonerManagement.entidades.Consumible;
import mx.gob.ceasonora.tonerManagement.gui.administrar.AdministrarConsumibles;
import mx.gob.ceasonora.tonerManagement.gui.administrar.nuevo.NuevoConsumible;
import mx.gob.ceasonora.tonerManagement.gui.administrar.ver.VerConsumible;
import mx.gob.ceasonora.tonerManagement.implementaciones.ConsumibleImp;
import mx.gob.ceasonora.tonerManagement.instancias.InstanciaConexion;
import mx.gob.ceasonora.tonerManagement.interfaces.ConsumibleInt;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author kevin
 */
public class RevisarInventario extends javax.swing.JInternalFrame {
    InstanciaConexion conexion = InstanciaConexion.getInstanciaConexion();
    ConsumibleInt conImp = new ConsumibleImp();
    DefaultTableModel modelo;
    String[] titulos = {"ID", "# Producto", "Nombre", "Cantidad"};
    List<Consumible> faltantes;
    List<Consumible> escasos;
    List<Consumible> consumibles;
    public static Consumible consumible;

    /**
     * Creates new form AdministrarHerramientas
     */
    public RevisarInventario() {
        initComponents();
        mostrarGroup.add(faltantesButton);
        mostrarGroup.add(escasosButton);
        
        faltantes = MenuPrincipal.faltantes;
        escasos = MenuPrincipal.escasos;
        
        modelo = new DefaultTableModel();
        consumiblesTable.setModel(modelo);
        modelo.setColumnIdentifiers(titulos);
        
        try {
            if(!faltantes.isEmpty()){
                consumibles = faltantes;
                faltantesButton.setSelected(true);
            }else if(!escasos.isEmpty()){
                consumibles = escasos;
                escasosButton.setSelected(true);
            }
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar los datos en la tabla");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mostrarGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        faltantesButton = new javax.swing.JRadioButton();
        escasosButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        consumiblesTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        reporteFaltantesButton = new javax.swing.JButton();
        reporteEscasosButton = new javax.swing.JButton();
        administrarConsumiblesButton = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consumibles Faltantes/Escasos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        faltantesButton.setText("Faltantes");
        faltantesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faltantesButtonActionPerformed(evt);
            }
        });

        escasosButton.setText("Escasos");
        escasosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escasosButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(faltantesButton)
                .addGap(96, 96, 96)
                .addComponent(escasosButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faltantesButton)
                    .addComponent(escasosButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        consumiblesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "# Producto", "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(consumiblesTable);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        reporteFaltantesButton.setText("Reporte de Faltantes");
        reporteFaltantesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteFaltantesButtonActionPerformed(evt);
            }
        });

        reporteEscasosButton.setText("Reporte de Escasos");
        reporteEscasosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEscasosButtonActionPerformed(evt);
            }
        });

        administrarConsumiblesButton.setText("Administrar Consumibles");
        administrarConsumiblesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarConsumiblesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(reporteFaltantesButton)
                .addGap(37, 37, 37)
                .addComponent(reporteEscasosButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(administrarConsumiblesButton)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reporteFaltantesButton)
                    .addComponent(reporteEscasosButton)
                    .addComponent(administrarConsumiblesButton))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void faltantesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faltantesButtonActionPerformed

        modelo.setRowCount(0);
        try {
            consumibles = faltantes;
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_faltantesButtonActionPerformed

    private void escasosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escasosButtonActionPerformed

        modelo.setRowCount(0);
        try {
            consumibles = escasos;
            for(Consumible con: consumibles){
                Object[] o = new Object[4];
                o[0] = con.getId();
                o[1] = con.getCodigoProducto();
                o[2] = con.getNombre();
                o[3] = con.getCantidad();
                
                modelo.addRow(o);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_escasosButtonActionPerformed

    private void administrarConsumiblesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarConsumiblesButtonActionPerformed

        AdministrarConsumibles administrar = new AdministrarConsumibles();
        getDesktopPane().add(administrar);
        administrar.setVisible(true);
        
    }//GEN-LAST:event_administrarConsumiblesButtonActionPerformed

    private void reporteFaltantesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteFaltantesButtonActionPerformed

        try {
            JDialog espera = new JDialog();
            espera.setLocationRelativeTo(null);
            espera.setTitle("Generando reporte...");
            espera.pack();
            espera.setVisible(true);
            
            conexion.conexion();
            JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_consumible_faltantes.jasper", null, conexion.con);
            JasperViewer.viewReport(jp, false);
            espera.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_reporteFaltantesButtonActionPerformed

    private void reporteEscasosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEscasosButtonActionPerformed

        try {
            JDialog espera = new JDialog();
            espera.setLocationRelativeTo(null);
            espera.setTitle("Generando reporte...");
            espera.pack();
            espera.setVisible(true);
            
            conexion.conexion();
            JasperPrint jp = JasperFillManager.fillReport("src\\reporte\\reporte_consumible_escasos.jasper", null, conexion.con);
            JasperViewer.viewReport(jp, false);
            espera.setVisible(false);

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_reporteEscasosButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administrarConsumiblesButton;
    private javax.swing.JTable consumiblesTable;
    private javax.swing.JRadioButton escasosButton;
    private javax.swing.JRadioButton faltantesButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup mostrarGroup;
    private javax.swing.JButton reporteEscasosButton;
    private javax.swing.JButton reporteFaltantesButton;
    // End of variables declaration//GEN-END:variables
}
